##########################################################################################################################
# File automatically-generated by tool: [projectgenerator] version: [4.5.0-B34] date: [Fri Oct 17 11:31:10 CST 2025] 
##########################################################################################################################

# ------------------------------------------------
# Generic Makefile (based on gcc)
#
# ChangeLog :
#	2017-02-10 - Several enhancements + project update mode
#   2015-07-22 - first version
# ------------------------------------------------

######################################
# target
######################################
TARGET = ExpansionBoard


######################################
# building variables
######################################
# debug build?
# debug option
#-g0	no debug information
#-g1	minimal debug information
#-g		default debug information
#-g3	maximal debug information
DEBUG = g3

# optimization
# -O0 		no optimization
# -O1 		
# -O2
# -O3
# -Os 		optimize for size
# -Ofast 	optimize for speed
# -Og 		optimize for debugging
OPT = -O2

# C standard
CSTD = -std=gnu17

# C++ standard
CPPSTD = -std=gnu++17

VERBOSE = 0

#######################################
# paths
#######################################
# Build path
BUILD_DIR = build

CORE_DIR = Dotech2024-Core

CORE_MK_DIR = $(CORE_DIR)/Dotech-Core.mk

LDSCRIPT_NMAE = STM32F103C8Tx_FLASH.ld

######################################
# source
######################################
# C sources
C_SOURCES =  \
Core/Src/main.c \
Core/Src/gpio.c \
Core/Src/stm32f1xx_it.c \
Core/Src/stm32f1xx_hal_msp.c \
Drivers/STM32F1xx_HAL_Driver/Src/stm32f1xx_hal_gpio_ex.c \
Drivers/STM32F1xx_HAL_Driver/Src/stm32f1xx_hal_tim.c \
Drivers/STM32F1xx_HAL_Driver/Src/stm32f1xx_hal_tim_ex.c \
Drivers/STM32F1xx_HAL_Driver/Src/stm32f1xx_hal.c \
Drivers/STM32F1xx_HAL_Driver/Src/stm32f1xx_hal_rcc.c \
Drivers/STM32F1xx_HAL_Driver/Src/stm32f1xx_hal_rcc_ex.c \
Drivers/STM32F1xx_HAL_Driver/Src/stm32f1xx_hal_gpio.c \
Drivers/STM32F1xx_HAL_Driver/Src/stm32f1xx_hal_dma.c \
Drivers/STM32F1xx_HAL_Driver/Src/stm32f1xx_hal_cortex.c \
Drivers/STM32F1xx_HAL_Driver/Src/stm32f1xx_hal_pwr.c \
Drivers/STM32F1xx_HAL_Driver/Src/stm32f1xx_hal_flash.c \
Drivers/STM32F1xx_HAL_Driver/Src/stm32f1xx_hal_flash_ex.c \
Drivers/STM32F1xx_HAL_Driver/Src/stm32f1xx_hal_exti.c \
Core/Src/system_stm32f1xx.c \
Core/Src/can.c \
Drivers/STM32F1xx_HAL_Driver/Src/stm32f1xx_hal_can.c \
Core/Src/i2c.c \
Drivers/STM32F1xx_HAL_Driver/Src/stm32f1xx_hal_i2c.c \
Core/Src/stm32f1xx_hal_timebase_tim.c \
Core/Src/spi.c \
Drivers/STM32F1xx_HAL_Driver/Src/stm32f1xx_hal_spi.c \
Core/Src/dma.c \
Core/Src/tim.c \
Core/Src/sysmem.c \
Core/Src/syscalls.c \
Core/Src/usart.c \
Drivers/STM32F1xx_HAL_Driver/Src/stm32f1xx_hal_uart.c
#test begin
#test begin#test begin#test begin#test begin#test begin#Core/Src/sysmem.c \
Core/Src/syscalls.c
#test end

# CPP sources
CPP_SOURCES =  \
$(wildcard Core/Src/*.cpp)\
$(wildcard APP/*.cpp)

# CPP compiled
CPP_COMPILED = 

# ASM sources
ASM_SOURCES =  \
startup_stm32f103xb.s

# macros for gcc
# AS defines
AS_DEFS = 

# C defines
C_DEFS =  \
-DUSE_HAL_DRIVER \
-DSTM32F103xB

# AS includes
AS_INCLUDES = 

# C includes
C_INCLUDES =  \
-ICore/Inc \
-IDrivers/STM32F1xx_HAL_Driver/Inc \
-IDrivers/STM32F1xx_HAL_Driver/Inc/Legacy \
-IDrivers/CMSIS/Device/ST/STM32F1xx/Include \
-IDrivers/CMSIS/Include \
-IAPP

include Rules.mk

#######################################
# J-Link Flash Section
#######################################
# 定义芯片型号和接口
#######################################
# J-Link Flash Section
#######################################
JLINK_DEVICE = STM32F103C8
JLINK_IF = SWD
JLINK_SPEED = 4000

flash: $(BUILD_DIR)/$(TARGET).elf
	@echo r > flash.jlink
	@echo h >> flash.jlink
	@echo loadfile $(BUILD_DIR)/$(TARGET).elf >> flash.jlink
	@echo r >> flash.jlink
	@echo g >> flash.jlink
	@echo q >> flash.jlink
	JLink.exe -device $(JLINK_DEVICE) -if $(JLINK_IF) -speed $(JLINK_SPEED) -autoconnect 1 -CommandFile flash.jlink
# 修改这里：增加 -f 强制删除且不报错，兼容性更好
	-rm -f flash.jlink